### ISSUE TITLE
Mercury Parser shutting down on 15.04.2019

### ISSUE THREAD

**Issue by ksiazkowicz** [Maledictus/harbour-linksbag#11]
Just a heads up, I got an email from Postlight (team behind Mercury Parser).

Mercury Parser which is currently used for article view and offline mode IIRC got open-sourced and released as a JS library.
https://github.com/postlight/mercury-parser

With that change, API which we're currently using will be shut down, so we have to either do processing on device itself using the newly released lib or find some other solution.

**Comment by Maledictus** [comment]
Hi.
It's awful information.I am not sure that we can use js library. Is is
possible in sailfish and qml? We should try to find new standalone
solutions for parcing web pages.

пн, 11 февр. 2019 г. в 19:41, Maciej Janiszewski <notifications@github.com>:

**Comment by ksiazkowicz** [comment]
I guess we could, though JS support in QML was limited and I'm not sure if it would work. It would also break our current flow for caching articles for offline reading. Looks like they also open-sourced their Web API, so technically I could host it on my own server or AWS Lambda as a temporary solution.

**Comment by Maledictus** [comment]
Today I think about this problem too and what do you think about heroku?

**Comment by Maledictus** [comment]
@ksiazkowicz AWS Lambda is good idea too. I don't think that we will exceed limits of free usage
