### ISSUE TITLE
Can't login with Firefox account on Sailifish

### ISSUE THREAD

**Issue by jkonecny12** [Maledictus/harbour-linksbag#15]
I'm having issue with the build-in webkit for firefox login. Because of outdated webkit (I guess this is the reason) I'm getting white screen instead of the login page.

The best solution for me would be to use external browser to log into the application and avoid using webkit for login. What do you think?

**Comment by Maledictus** [comment]
I will see what I can do with this problem

**Comment by jkonecny12** [comment]
There is a workaround. You can try to log as google when a browser window will open cancel the login and that will return you back to the login where even firefox is possible.

It's not that easy but it's working.

**Comment by Maledictus** [comment]
fixed in 3.2.2

But there is a small problem: if you use firefox it will not login from the first attempt and you should make login again

**Comment by jkonecny12** [comment]
Thanks a lot for fixing this!
