### ISSUE TITLE
Authorize to pocket with google does not work

### ISSUE THREAD

**Issue by ninjarider** [Maledictus/harbour-linksbag#4]
Hi,
When trying to authorize linksbag with pocket the google button is not possible to click on. part of the screen with the buttons for facebook and google is darkened.
The Jolla phone is on Björnträsket OS level.

Regards

**Comment by Maledictus** [comment]
Sorry for so late answer but it is impossible now with qml webview, which I use for authorization.

**Comment by Maledictus** [comment]
Fixed
