### ISSUE TITLE
UX ideas

### ISSUE THREAD

**Issue by ksiazkowicz** [Maledictus/harbour-linksbag#5]
I'm enjoying using your app so far, but I think design and overall UX needs some work. I started doing some work on that in my own fork and I'm looking forward to hear your feedback and discuss these changes.

## Cover (bookmark list view)
![zrzut_ekranu_20171223_003](https://user-images.githubusercontent.com/1162358/34319922-1b50c780-e7ee-11e7-95e4-4e19abe31ee0.png)
Modelled after e-mail cover, shows a number of articles/bookmarks that are currently displayed with a proper header ("unread articles", "all articles", "favourite articles").

## Cover (article)
First image in article used as background if available, big title on the bottom.

## Bookmark list view
![zrzut_ekranu_20171223_005](https://user-images.githubusercontent.com/1162358/34320119-5233fe76-e7f2-11e7-9209-21470a2bbf77.png)
I think default view should by default show articles that are unread, just as in official Pocket app or Poki on Windows (btw. it's a really nicely designed app, if you're looking for inspiration). Unread toggle could be moved to menu to reduce the clutter, it's not an action that's being frequently used. An indicator could be represented by an icon or like in Feed Haven or built-in Mail app, with GlassItem. Bold on title seems unnecessary. It would be nice to have a thumbnail, but I'm not sure whether it's easy to implement at the moment. I'd like to do something about filters not being comfortable to access and I'd move search to another page since user already has to "toggle" that from pulley menu.

## Article/bookmark view
![zrzut_ekranu_20171223_006](https://user-images.githubusercontent.com/1162358/34320292-2eb5acb0-e7f7-11e7-875e-08b4615187ae.png)
URLs in text should use ambience highlight color. It lacks a header. A small indicator of how far we're in the article would be great. Also, app should remember the point at which we stopped reading.

**Comment by Maledictus** [comment]
Very interesting ideas. I try to implement most of them, but after workibg with google authoruzation, which still have not work.

**Comment by ksiazkowicz** [comment]
Thanks! I implemented some of the things mentioned here in my fork at: https://github.com/ksiazkowicz/harbour-linksbag

It's a work in progress, I'll send you a PR when it's done so you can review and merge my changes.

**Comment by ksiazkowicz** [comment]
Cover used when in article view:
![zrzut_ekranu_20171223_007](https://user-images.githubusercontent.com/1162358/34320963-7d098ec4-e804-11e7-9405-f6a2541775a3.png)
Not sure if source shouldn't be put in there too.

**Comment by ksiazkowicz** [comment]
I made a few more changes in my fork, like putting thumbnail image behind a list item (not sure if this isn't a bit too much):
![zrzut_ekranu_20171223_009](https://user-images.githubusercontent.com/1162358/34322069-ce4abf42-e81d-11e7-890e-7cda37cd1b46.png)

While readable version of article is being loaded, thumbnail fills the whole screen, it's also a background for a header now.
![zrzut_ekranu_20171223_010](https://user-images.githubusercontent.com/1162358/34322079-f5dcd162-e81d-11e7-9abd-2da8495d96f0.png)

It then collapses, taking max 25% of screen height. Current animation seems to be a bit too slow for my taste.
![zrzut_ekranu_20171223_011](https://user-images.githubusercontent.com/1162358/34322083-149bac04-e81e-11e7-883b-0968f8f56d12.png)

There are also changes in the way I download articles from Readability, it no longer grabs stuff from outside of <body> tag, it removes <img> tag with the same image as in thumbnail and parses all pages. There are some CSS issues I'd like to fix before sending you a PR. Readability stuff is in a separate component now, something that might be useful while implementing offline mode. Even just saving whatever we get from Readability somewhere on a phone might be a big improvement (offline mode is IMHO the best feature from Pocket).

**Comment by Maledictus** [comment]
And one more: I have added google authorization, so your should pull from my repository to fix conflicts. 
Thank you for your efforts
